ublox:
  ros__parameters:

    debug: 1

    device: /dev/ttyUBLOX
    frame_id: gps

    config_on_startup: false

    uart1:
      baudrate: 230400

    rate: 10.0 # Hz

    # message publishers
    publish:
      all: false
      nav:
        all: true
      nmea: true