ublox:
  ros__parameters:

    debug: 1

    device: /dev/ttyUBLOX
    frame_id: gps

    config_on_startup: false

    uart1:
      baudrate: 230400

    rate: 10.0 # Hz

    # diagnostics
    ignore_fix_timestamp: true
    # fix_frequency_tolerance: 0.15
    # fix_frequency_window: 10
    # timestamp_status_min: 0

    # message publishers
    publish:
      all: false
      nav:
        all: true
      nmea: true