diagnostic_aggregator:
  ros__parameters:
    pub_rate: 1.0
    path: CaBot
    discard:
      type: diagnostic_aggregator/DiscardAnalyzer
      path: discard
      contains:
        - "Push Button"
        - "realsense2_camera_manager_aligned_depth_to_color: Frequency Status"
        - "cabot_serial: Pressure"
        - "cabot_serial: Temperature"
        - "cabot_serial: Touch"
        - "cabot_can: Pressure"
        - "Rosserial Connection"
        - "cabot_serial: Serial Connection"
        - "rosserial_esp32: Serial Connection"

    hard_beacon:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: Beacon"
      contains:
        - "Beacon Scanner"
        - "Beacon Converter"
      remove_prefix:
        - "dbus_ibeacon_scanner: "
        - "ble_scan_converter: "

    # IMU (cabot_serial or cabot_can)
    hard_imu:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: IMU"
      contains:
        - "cabot_serial: IMU"
        - "cabot_can: IMU"
      remove_prefix:
        - "cabot_serial: "
        - "cabot_can: "

    hard_wifi:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: WiFi"
      contains:
        - "esp32_wifi_scan_converter: "
        - "rosserial_esp32: WiFi"
      remove_prefix:
        - "esp32_wifi_scan_converter: "
        - "rosserial_esp32: "
        
    # LiDAR (velodyne or hesai)
    hard_lidar:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: LiDAR"
      contains:
        - "velodyne_driver_node: "
        - "velodyne_transform_node: "
        - "hesai"
      remove_prefix:
        - "velodyne_driver_node: "
        - "velodyne_transform_node: "
        - "hesai_lidar: "

    # ublox
    discard_ublox:
      type: diagnostic_aggregator/DiscardAnalyzer
      path: discard
      contains:
        - "ublox: TMODE3"

    hard_ublox:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: ublox GNSS"
      contains:
        - "ublox: fix"

    soft_ntrip:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Soft: NTRIP client"
      contains:
        - "ntrip_client:"
      remove_prefix:
        - "ntrip_client:"
