name: Test Building Docker Image and Workspace

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-docker-image.yaml'
      - '**'
      - '!docker/home/**'
      - '!docker/*.sh'
      - '!docker/timezone/**'
      - '!docker/uid/**'

jobs:
  test_build:
    runs-on: ubuntu-20.04
    steps:
    # run test
    - name: Trigger Workflow in Sandbox
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.TOKEN }}" \
        https://api.github.com/repos/cmu-cabot/sandbox/dispatches \
        -d '{"event_type": "build-and-test"}'
      env:
        PAT: ${{ secrets.TOKEN }}

    - name: Maximize build space
      run:  |
            sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
            sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
            sudo rm -rf /opt/ghc
            echo "Available storage:"
            df -h

    - uses: actions/checkout@v4

    - name: Install vcs
      run: pip3 install vcstool

    - name: Prepare thirdparty repos
      run: ./setup-dependency.sh

    - name: Build images
      shell: bash
      run: ./build-docker.sh -p -i -w
