name: Test Building Docker Image and Workspace

on:
  push:
    branches:
      - "**"

jobs:
  build-navigation:
    uses: cmu-cabot/cabot-navigation/.github/workflows/build.yaml@yushim/docker-production-image
    with:
      target: navigation
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-localization:
    uses: cmu-cabot/cabot-navigation/.github/workflows/build.yaml@yushim/docker-production-image
    with:
      target: localization
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
