name: Run Unittest

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run_unittest:
    runs-on: ubuntu-20.04
    steps:
    - name: Maximize build space
      run:  |
            sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
            sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
            sudo rm -rf /opt/ghc
            echo "Available storage:"
            df -h

    - uses: actions/checkout@v4

    - name: Install vcs
      run: pip3 install vcstool

    - name: Prepare thirdparty repos
      run: ./setup-dependency.sh

    - name: Build images
      shell: bash
      run: ./build-docker.sh -p -i -w -u 1000

    - name: Run unittest
      shell: bash
      run: ./launch.sh -u
