name: Run Unittest

on:
  push:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run_unittest:
    runs-on: ubuntu-22.04
    steps:  
    - name: Maximize build space
      run:  |
            sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
            sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
            sudo rm -rf /opt/ghc
            echo "Available storage:"
            df -h
            docker system prune -a --volumes -f # delete unnecessary preinstalled docker images
            
    - uses: actions/checkout@v4
    
    - uses: docker/setup-qemu-action@v3

    - name: Install vcs
      run: pip3 install vcstool

    - name: Prepare thirdparty repos
      run: ./setup-dependency.sh

    - name: Pull images 
      shell: bash
      run:  |
             docker pull cmucal/cabot-navigation:latest
             docker tag cmucal/cabot-navigation:latest cabot-navigation-ros2
             docker tag cabot-navigation-ros2:latest cabot-navigation-bag:latest
             docker tag cabot-navigation-ros2:latest cabot-navigation-gazebo:latest
             docker tag cabot-navigation-ros2:latest cabot-navigation-gui:latest
             docker tag cabot-navigation-ros2:latest cabot-navigation-navigation:latest
             docker tag cabot-navigation-ros2:latest cabot-navigation-diagnostic:latest

             docker pull cmucal/cabot-localization:latest
             docker tag cmucal/cabot-localization:latest cabot-navigation-localization
             docker tag cabot-navigation-localization:latest cabot-navigation-mapping:latest
             docker tag cabot-navigation-localization:latest cabot-navigation-post-process:latest
             docker tag cabot-navigation-localization:latest cabot-navigation-rtk-gnss:latest

    - name: Run unittest
      shell: bash
      run:  |
             export HOST_UID=$(id -u)
             export HOST_GID=$(id -g)
             ./launch.sh -p -u -- -b -a
